'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase,TABLE} from '../lib/supabase'
import {Activity,AlertTriangle,ArrowUpRight,Bell,Car,CheckCircle2,ChevronLeft,ChevronRight,Clock3,Download,Filter,History,LayoutDashboard,LogIn,LogOut,Mail,MessageSquareText,RefreshCw,Search,ShieldCheck,Users,X} from 'lucide-react'
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'

const g=(r,...names)=>{for(const n of names) if(r?.[n]!==undefined&&r?.[n]!==null)return r[n]; return ''}
const bool=(v)=>v===true||String(v).toLowerCase()==='true'
const sentimentClass=s=>String(s).toLowerCase().includes('negative')?'neg':String(s).toLowerCase().includes('positive')?'pos':'neu'
const fmt=v=>{if(!v)return '—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('en',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}
const keyOf=r=>g(r,'created_at','id','ID','Job ID','job_id')
const isNegative=r=>String(g(r,'Sentiment','sentiment')).trim().toLowerCase().includes('negative')
const isEscalated=r=>String(g(r,'Route','route')).trim().toLowerCase().includes('needs manager')&&bool(g(r,'Manager Alert Sent','manager_alert_sent'))
const isApproved=r=>bool(g(r,'Approved','approved'))
const escPending=r=>isEscalated(r)&&!isApproved(r)
const sample=[]

export default function Page(){
 const [rows,setRows]=useState(sample),[loading,setLoading]=useState(true),[live,setLive]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(''),[sentiment,setSentiment]=useState('All'),[route,setRoute]=useState('All'),[branch,setBranch]=useState('All'),[range,setRange]=useState('All time'),[selected,setSelected]=useState(null),[page,setPage]=useState(1),[view,setView]=useState('overview'),[saving,setSaving]=useState(''),[user,setUser]=useState(null),[authReady,setAuthReady]=useState(false),[authBusy,setAuthBusy]=useState(false),[authError,setAuthError]=useState(''); const pageSize=8
 async function load(){setLoading(true);setError('');if(!process.env.NEXT_PUBLIC_SUPABASE_URL){setLoading(false);return} const {data,error}=await supabase.from(TABLE).select('*').order('created_at',{ascending:false}).limit(5000); if(error){setError(error.message);setLive(false)} else {setRows(data||[]);setLive(true)} setLoading(false)}
 useEffect(()=>{let mounted=true;supabase.auth.getUser().then(({data})=>{if(mounted){setUser(data.user||null);setAuthReady(true)}});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user||null);setAuthReady(true)});return()=>{mounted=false;subscription.unsubscribe()}},[])
 useEffect(()=>{if(!authReady||!user)return;load();if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return; const c=supabase.channel('feedback-dashboard-v3').on('postgres_changes',{event:'*',schema:'public',table:TABLE},()=>load()).subscribe();return()=>supabase.removeChannel(c)},[authReady,user?.id])
 async function signIn(email,password){setAuthBusy(true);setAuthError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setAuthError(error.message);setAuthBusy(false)}
 async function signOut(){await supabase.auth.signOut();setRows([]);setLive(false);setSelected(null)}
 async function approve(row){const key=keyOf(row);if(!key){setError('This record has no usable unique key.');return}if(!user){setError('Your manager session has expired. Please sign in again.');return}setSaving(String(key));setError('');const keyCol=row.created_at!==undefined?'created_at':row.id!==undefined?'id':row.ID!==undefined?'ID':row['Job ID']!==undefined?'Job ID':'job_id';const payload={Approved:true,'Approved At':new Date().toISOString(),'Approved By':user.email||user.id};const {error}=await supabase.from(TABLE).update(payload).eq(keyCol,key);if(error)setError(error.message);else {setSelected(null);await load()}setSaving('')}
 const filtered=useMemo(()=>rows.filter(r=>{const text=Object.values(r).join(' ').toLowerCase();const d=new Date(g(r,'Date Logged','date_logged','created_at'));const days=range==='Today'?1:range==='7 days'?7:range==='30 days'?30:null;const dateOk=!days||(!isNaN(d)&&Date.now()-d.getTime()<=days*86400000);return dateOk&&(!search||text.includes(search.toLowerCase()))&&(sentiment==='All'||g(r,'Sentiment','sentiment')===sentiment)&&(route==='All'||g(r,'Route','route')===route)&&(branch==='All'||g(r,'Branch','branch')===branch)}),[rows,search,sentiment,route,branch,range])
 const stats=useMemo(()=>{const scores=filtered.map(r=>Number(g(r,'Score','score'))).filter(Number.isFinite);return{total:filtered.length,avg:scores.length?(scores.reduce((a,b)=>a+b,0)/scores.length).toFixed(1):'—',neg:filtered.filter(r=>String(g(r,'Sentiment','sentiment')).toLowerCase().includes('negative')).length,pending:filtered.filter(escPending).length,approved:filtered.filter(r=>isEscalated(r)&&isApproved(r)).length}},[filtered])
 const trend=useMemo(()=>{const m={};[...filtered].reverse().forEach(r=>{const d=new Date(g(r,'Date Logged','date_logged','created_at'));if(!isNaN(d)){const k=d.toLocaleDateString('en',{month:'short',day:'numeric'});m[k]=(m[k]||0)+1}});return Object.entries(m).map(([date,value])=>({date,value}))},[filtered])
 const sentiments=['All',...new Set(rows.map(r=>g(r,'Sentiment','sentiment')).filter(Boolean))],routes=['All',...new Set(rows.map(r=>g(r,'Route','route')).filter(Boolean))],branches=['All',...new Set(rows.map(r=>g(r,'Branch','branch')).filter(Boolean))]
 const viewRows=view==='attention'?filtered.filter(escPending):view==='history'?filtered.filter(r=>isEscalated(r)&&isApproved(r)):filtered;const pages=Math.max(1,Math.ceil(viewRows.length/pageSize)),shown=viewRows.slice((page-1)*pageSize,page*pageSize)
 useEffect(()=>setPage(1),[search,sentiment,route,branch,range,view])
 function go(v){setView(v);setSelected(null)}
 function exportCsv(){const rs=viewRows;if(!rs.length)return;const cols=Object.keys(rs[0]);const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv=[cols.map(q).join(','),...rs.map(r=>cols.map(c=>q(r[c])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`feedback-${view}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
 if(!authReady)return <div className="authShell"><div className="authCard authLoading"><ShieldCheck/><h2>Securing dashboard</h2><p>Checking your manager session...</p></div></div>
 if(!user)return <Login signIn={signIn} busy={authBusy} error={authError}/>
 return <main><aside><div className="brand"><div className="logo">CC</div><div><b>Car Care</b><small>Experience Intelligence</small></div></div><nav><a className={view==='overview'?'active':''} onClick={()=>go('overview')}><LayoutDashboard/>Overview</a><a className={view==='feedback'?'active':''} onClick={()=>go('feedback')}><MessageSquareText/>All Feedback</a><a className={view==='attention'?'active':''} onClick={()=>go('attention')}><AlertTriangle/>Attention {stats.pending>0&&<i className="navCount">{stats.pending}</i>}</a><a className={view==='history'?'active':''} onClick={()=>go('history')}><History/>Approval History</a><a className={view==='customers'?'active':''} onClick={()=>go('customers')}><Users/>Customers</a><a className={view==='vehicles'?'active':''} onClick={()=>go('vehicles')}><Car/>Vehicles</a></nav><div className="sideFoot"><ShieldCheck/><div><b>System healthy</b><small>{live?'Connected to Supabase':'Waiting for connection'}</small></div></div></aside>
 <section className="content"><header><div><p className="eyebrow">CUSTOMER EXPERIENCE</p><h1>{view==='attention'?'Manager Attention':view==='history'?'Approval History':view==='feedback'?'All Customer Feedback':view==='customers'?'Customers':view==='vehicles'?'Vehicles':'Feedback Intelligence'}</h1><p>{view==='attention'?'Review escalated customer messages, understand the sentiment, and close the loop.':view==='history'?'A clean audit trail of escalations already reviewed by management.':view==='customers'?'Understand each customer’s feedback history, sentiment, and service experience.':view==='vehicles'?'See feedback patterns and sentiment across vehicles in your customer base.':'See every customer signal, understand what matters, and act quickly.'}</p></div><div className="headerActions"><span className={'live '+(live?'on':'')}><i></i>{live?'Live':'Offline'}</span><button className="icon" onClick={load}><RefreshCw size={18}/></button><button className="icon"><Bell size={18}/></button><div className="userChip"><span>{(user.email||'M').slice(0,1).toUpperCase()}</span><div><b>Manager</b><small>{user.email}</small></div></div><button className="signOut" onClick={signOut} title="Sign out"><LogOut size={17}/>Sign out</button></div></header>
 {error&&<div className="errorBanner"><AlertTriangle/> {error}</div>}
 <div className="filters"><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customers, feedback, email..."/></div><Select icon={<Clock3/>} value={range} set={setRange} options={['All time','Today','7 days','30 days']}/><Select icon={<Filter/>} value={branch} set={setBranch} options={branches}/><Select value={sentiment} set={setSentiment} options={sentiments}/><Select value={route} set={setRoute} options={routes}/><button className="export" onClick={exportCsv}><Download/>Export</button></div>
 {view==='overview'&&<><div className="cards"><Card label="Total feedback" value={stats.total} sub="records in current view" icon={<MessageSquareText/>}/><Card label="Average score" value={stats.avg} sub="across filtered feedback" icon={<Activity/>}/><Card label="Negative feedback" value={stats.neg} sub={stats.total?`${Math.round(stats.neg/stats.total*100)}% of current view`:'No feedback'} icon={<ArrowUpRight/>} warn onClick={()=>{setSentiment('Negative');go('feedback')}}/><Card label="Needs approval" value={stats.pending} sub="manager action required" icon={<AlertTriangle/>} warn={stats.pending>0} onClick={()=>go('attention')}/></div>
 <div className="grid"><div className="panel chart"><PanelTitle title="Feedback activity" sub="Volume of feedback received"/><div className="chartBox">{trend.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid vertical={false} stroke="#eef1f5"/><XAxis dataKey="date" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="value" stroke="#2b6ef2" fill="#e9f0ff" strokeWidth={2.5}/></AreaChart></ResponsiveContainer>:<Empty/>}</div></div><div className="panel"><PanelTitle title="Sentiment pulse" sub="How customers are feeling"/><Sentiments rows={filtered}/></div></div></>}
 {view==='attention'&&<Attention rows={viewRows} approve={approve} saving={saving} select={setSelected}/>} 
 {view==='history'&&<HistoryView rows={viewRows} select={setSelected}/>} 
 {view==='customers'&&<CustomersView rows={filtered} select={setSelected}/>}
 {view==='vehicles'&&<VehiclesView rows={filtered} select={setSelected}/>}
 {(view==='overview'||view==='feedback')&&<FeedbackTable rows={shown} total={viewRows.length} page={page} pages={pages} setPage={setPage} select={setSelected}/>} 
 {selected&&<Drawer row={selected} close={()=>setSelected(null)} approve={approve} saving={saving}/>} {loading&&<div className="loading">Syncing dashboard…</div>}</section></main>}

function CustomersView({rows,select}){
 const groups=useMemo(()=>{const m=new Map();for(const r of rows){const id=String(g(r,'Customer ID','customer_id')||g(r,'Email','email')||g(r,'Customer Name','customer_name')||'Unknown');if(!m.has(id))m.set(id,[]);m.get(id).push(r)}return [...m.entries()].map(([id,items])=>{const latest=[...items].sort((a,b)=>new Date(g(b,'Date Logged','date_logged','created_at'))-new Date(g(a,'Date Logged','date_logged','created_at')))[0];const scores=items.map(x=>Number(g(x,'Score','score'))).filter(Number.isFinite);return{id,items,latest,name:g(latest,'Customer Name','customer_name')||'Unknown customer',email:g(latest,'Email','email'),count:items.length,negative:items.filter(isNegative).length,avg:scores.length?(scores.reduce((a,b)=>a+b,0)/scores.length).toFixed(1):'—'}}).sort((a,b)=>b.count-a.count)},[rows]);
 return <div className="panel tablePanel"><PanelTitle title="Customer directory" sub={`${groups.length} customers in the current filters`} right={<span className="tiny">Click a customer to open their latest feedback</span>}/><div className="tableWrap"><table><thead><tr><th>Customer</th><th>Feedback</th><th>Avg score</th><th>Negative</th><th>Latest sentiment</th><th>Latest visit</th></tr></thead><tbody>{groups.map(c=><tr key={c.id} onClick={()=>select(c.latest)}><td><div className="person"><span>{c.name.slice(0,1)}</span><div><b>{c.name}</b><small>{c.email||c.id}</small></div></div></td><td><strong>{c.count}</strong></td><td><strong className={Number(c.avg)<0?'red':''}>{c.avg}</strong></td><td>{c.negative}</td><td><Badge type={sentimentClass(g(c.latest,'Sentiment','sentiment'))}>{g(c.latest,'Sentiment','sentiment')||'—'}</Badge></td><td>{fmt(g(c.latest,'Date Logged','date_logged','created_at'))}</td></tr>)}</tbody></table></div>{!groups.length&&<div className="listEmpty">No customers match these filters.</div>}</div>
}
function VehiclesView({rows,select}){
 const groups=useMemo(()=>{const m=new Map();for(const r of rows){const car=String(g(r,'Car','car')||'Unknown vehicle').trim();if(!m.has(car))m.set(car,[]);m.get(car).push(r)}return [...m.entries()].map(([car,items])=>{const latest=[...items].sort((a,b)=>new Date(g(b,'Date Logged','date_logged','created_at'))-new Date(g(a,'Date Logged','date_logged','created_at')))[0];const scores=items.map(x=>Number(g(x,'Score','score'))).filter(Number.isFinite);return{car,items,latest,count:items.length,customers:new Set(items.map(x=>g(x,'Customer ID','customer_id')||g(x,'Email','email')||g(x,'Customer Name','customer_name'))).size,negative:items.filter(isNegative).length,avg:scores.length?(scores.reduce((a,b)=>a+b,0)/scores.length).toFixed(1):'—'}}).sort((a,b)=>b.count-a.count)},[rows]);
 return <div className="vehicleGrid">{groups.map(v=><article className="vehicleCard" key={v.car} onClick={()=>select(v.latest)}><div className="vehicleIcon"><Car/></div><div className="vehicleHead"><div><span className="eyebrow">VEHICLE</span><h3>{v.car}</h3></div><Badge type={sentimentClass(g(v.latest,'Sentiment','sentiment'))}>{g(v.latest,'Sentiment','sentiment')||'—'}</Badge></div><div className="vehicleStats"><div><span>Feedback</span><b>{v.count}</b></div><div><span>Customers</span><b>{v.customers}</b></div><div><span>Avg score</span><b className={Number(v.avg)<0?'red':''}>{v.avg}</b></div><div><span>Negative</span><b>{v.negative}</b></div></div><p>Latest feedback · {fmt(g(v.latest,'Date Logged','date_logged','created_at'))}</p></article>)}{!groups.length&&<div className="panel successEmpty"><Car/><h2>No vehicles found</h2><p>No vehicle records match the current filters.</p></div>}</div>
}
function Attention({rows,approve,saving,select}){return <div className="attentionGrid">{rows.length?rows.map(r=><article className="attentionCard" key={String(keyOf(r))}><div className="attentionTop"><div><span className="eyebrow">ESCALATED FEEDBACK</span><h3>{g(r,'Customer Name','customer_name')||'Unknown customer'}</h3><p>{g(r,'Car','car')} · {g(r,'Branch','branch')} · {fmt(g(r,'Date Logged','date_logged','created_at'))}</p></div><Badge type={sentimentClass(g(r,'Sentiment','sentiment'))}>{g(r,'Sentiment','sentiment')||'Unclassified'}</Badge></div><div className="messageQuote">“{g(r,'Feedback Text','feedback_text')||'No feedback text'}”</div><div className="managerFacts"><div><span>Score</span><b className={Number(g(r,'Score','score'))<0?'red':''}>{g(r,'Score','score')||'—'}</b></div><div><span>Route</span><b>{g(r,'Route','route')||'—'}</b></div><div><span>Repeat negative</span><b>{bool(g(r,'Repeat Negative Customer','repeat_negative_customer'))?'Yes':'No'}</b></div></div><Section title="AI analysis" text={g(r,'Reason','reason')}/><div className="attentionActions"><button className="secondary" onClick={()=>select(r)}>Read full record</button><button className="approve" disabled={saving===String(keyOf(r))} onClick={()=>approve(r)}><CheckCircle2/>{saving===String(keyOf(r))?'Approving…':'Approve & close'}</button></div></article>):<div className="panel successEmpty"><CheckCircle2/><h2>All caught up</h2><p>There are no escalated messages waiting for manager approval.</p></div>}</div>}
function HistoryView({rows,select}){return <div className="panel"><PanelTitle title="Reviewed escalations" sub={`${rows.length} approved records`}/><div className="historyList">{rows.map(r=><button key={String(keyOf(r))} onClick={()=>select(r)}><CheckCircle2/><div><b>{g(r,'Customer Name','customer_name')}</b><small>{g(r,'Feedback Text','feedback_text')}</small></div><Badge type={sentimentClass(g(r,'Sentiment','sentiment'))}>{g(r,'Sentiment','sentiment')}</Badge><span>{fmt(g(r,'Approved At','approved_at','Date Logged','date_logged'))}</span></button>)}</div></div>}
function FeedbackTable({rows,total,page,pages,setPage,select}){return <div className="panel tablePanel"><PanelTitle title="Customer feedback" sub={`${total} matching records`} right={<span className="tiny">Click any row to inspect details</span>}/><div className="tableWrap"><table><thead><tr><th>Customer</th><th>Vehicle</th><th>Score</th><th>Sentiment</th><th>Route</th><th>Approval</th><th>Logged</th></tr></thead><tbody>{rows.map(r=><tr key={String(keyOf(r))} onClick={()=>select(r)}><td><div className="person"><span>{String(g(r,'Customer Name','customer_name')||'?').slice(0,1)}</span><div><b>{g(r,'Customer Name','customer_name')||'Unknown'}</b><small>{g(r,'Email','email')}</small></div></div></td><td>{g(r,'Car','car')||'—'}</td><td><strong className={Number(g(r,'Score','score'))<0?'red':''}>{g(r,'Score','score')}</strong></td><td><Badge type={sentimentClass(g(r,'Sentiment','sentiment'))}>{g(r,'Sentiment','sentiment')||'—'}</Badge></td><td><Badge>{g(r,'Route','route')||'—'}</Badge></td><td>{isEscalated(r)?<Badge type={isApproved(r)?'pos':'neg'}>{isApproved(r)?'Approved':'Pending'}</Badge>:<span className="muted">—</span>}</td><td>{fmt(g(r,'Date Logged','date_logged','created_at'))}</td></tr>)}</tbody></table></div><div className="pagination"><span>{total} records</span><div><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></button><b>{page} / {pages}</b><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}><ChevronRight/></button></div></div></div>}
function Sentiments({rows}){return <div className="sentList">{['Highly Positive','Positive','Neutral','Negative'].map(s=>{const n=rows.filter(r=>g(r,'Sentiment','sentiment')===s).length,p=rows.length?Math.round(n/rows.length*100):0;return <div className="sentRow" key={s}><div><span className={'dot '+sentimentClass(s)}></span><b>{s}</b><em>{n}</em></div><div className="bar"><i className={sentimentClass(s)} style={{width:p+'%'}}></i></div><small>{p}%</small></div>})}</div>}
function Login({signIn,busy,error}){const [email,setEmail]=useState(''),[password,setPassword]=useState('');async function submit(e){e.preventDefault();if(!email||!password)return;await signIn(email.trim(),password)}return <div className="authShell"><div className="authBrand"><div className="authLogo">CC</div><div><b>Car Care</b><small>Experience Intelligence</small></div></div><form className="authCard" onSubmit={submit}><div className="authShield"><ShieldCheck/></div><p className="eyebrow">SECURE MANAGER ACCESS</p><h1>Feedback Intelligence</h1><p className="authIntro">Sign in with your authorized manager account to review customer feedback and approve escalations.</p>{error&&<div className="authError"><AlertTriangle/>{error}</div>}<label><span>Email address</span><div className="authInput"><Mail/><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="manager@company.com" required/></div></label><label><span>Password</span><div className="authInput"><ShieldCheck/><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" required/></div></label><button className="loginButton" disabled={busy}><LogIn/>{busy?'Signing in...':'Sign in securely'}</button><small className="authNote">Access is restricted to authorized staff.</small></form></div>}
function Select({value,set,options,icon}){return <label className="select">{icon}<select value={value} onChange={e=>set(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Card({label,value,sub,icon,warn,onClick}) {return <div className={'card '+(onClick?'clickable':'')} onClick={onClick}><div className={'cardIcon '+(warn?'warning':'')}>{icon}</div><p>{label}</p><h2>{value}</h2><small>{sub}</small></div>}
function PanelTitle({title,sub,right}){return <div className="panelTitle"><div><h3>{title}</h3><p>{sub}</p></div>{right}</div>}
function Badge({children,type=''}){return <span className={'badge '+type}>{children}</span>}
function Empty(){return <div className="empty">No data for this filter.</div>}
function Drawer({row,close,approve,saving}){const fields=[['Customer ID',g(row,'Customer ID','customer_id')],['Job ID',g(row,'Job ID','job_id')],['Email',g(row,'Email','email')],['Branch',g(row,'Branch','branch')],['Vehicle',g(row,'Car','car')],['Confidence',String(g(row,'Confidence','confidence'))],['Repeat negative',String(g(row,'Repeat Negative Customer','repeat_negative_customer'))],['Approved',String(isApproved(row))],['Approved At',fmt(g(row,'Approved At','approved_at'))],['Approved By',g(row,'Approved By','approved_by')]];return <div className="overlay" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><p className="eyebrow">FEEDBACK DETAIL</p><h2>{g(row,'Customer Name','customer_name')}</h2><p className="drawerMeta">{g(row,'Car','car')} · {g(row,'Branch','branch')} · {fmt(g(row,'Date Logged','date_logged','created_at'))}</p><div className="scoreLine"><Badge type={sentimentClass(g(row,'Sentiment','sentiment'))}>{g(row,'Sentiment','sentiment')}</Badge><strong>Score {g(row,'Score','score')}</strong></div><Section title="Customer feedback" text={g(row,'Feedback Text','feedback_text')}/><Section title="AI analysis" text={g(row,'Reason','reason')}/><Section title="Route" text={g(row,'Route','route')}/><Section title="Draft response" text={g(row,'Draft Response','draft_response')||'No draft response generated.'}/><div className="details">{fields.map(([k,v])=><div key={k}><span>{k}</span><b>{v||'—'}</b></div>)}</div>{isEscalated(row)&&!isApproved(row)&&<button className="approve wide" disabled={saving===String(keyOf(row))} onClick={()=>approve(row)}><CheckCircle2/>{saving===String(keyOf(row))?'Approving…':'Approve & close escalation'}</button>}</aside></div>}
function Section({title,text}){return <div className="section"><small>{title}</small><p>{text||'—'}</p></div>}
